### ISSUE TITLE
cuda libraries are not configured properly in Owlsnest

### ISSUE THREAD

**Issue by vgnshm** [vgnshm/templesoftware#8]
The following shows that cuda is not configured even for previous lammps version.
$ module load lammps/29Sep2021
The following have been reloaded with a version change:
  1) cuda/9.0.176 => cuda/11.2.1     2) gcc/6.4 => gcc/9.3.0     3) lammps/16Mar2018 => lammps/29Sep2021
$ lmp_gpu -h
lmp_gpu: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by akohlmey** [comment]
> The following shows that cuda is not configured even for previous lammps version

That is not correct. 

There are no GPUs on the login nodes, so there is no CUDA driver installed, hence no libcuda.so.1 in the system path.
But there *are* GPUs available on the nodes of the "large" queue, and there the `lmp_gpu` command works as expected.
CUDA executables *can* be compiled on the login nodes because the CUDA software contains stub libraries, they just cannot be used to run executables.

```
[akohlmey@login1 ~]$ qsub -q large -I 
qsub: waiting for job 1373983 to start
qsub: job 1373983 ready

----------------------------------------
Begin Batch Job Prologue Mon Apr  3 13:12:36 EDT 2023
Job ID:           1373983
Username:         akohlmey
Group:            hpc
Job Name:         STDIN
Resources List:   neednodes=1:ppn=16,walltime=00:30:00,nodes=1:ppn=16
Queue:            large
Account:          
Nodes:            g006 
----------------------------------------
End Batch Job Prologue Mon Apr  3 13:12:37 EDT 2023
----------------------------------------
[akohlmey@g006 ~]$ module load lammps/29Sep2021 

The following have been reloaded with a version change:
  1) gcc/4.8 => gcc/9.3.0

[akohlmey@g006 ~]$ lmp_gpu -h

Large-scale Atomic/Molecular Massively Parallel Simulator - 29 Sep 2021 - Update 2
Git info (stable / patch_29Sep2021_update2)

Usage example: lmp_gpu -var t 300 -echo screen -in in.alloy
```
